select * from cars;
select * from sales;
select * from salespersons;

-- Question 1. What are the details of all cars purchased in the year 2022?

select cars.car_id, make, type, style, cost_$
from cars
join sales on cars.car_id = sales.car_id 
and extract(year from purchase_date) = 2022;


-- Question 2. What is the total number of cars sold by each salesperson?

select name, count(car_id) total_cars_sold
from sales
join salespersons on sales.salesman_id = salespersons.salesman_id
group by name 

-- Question 3. What is the total revenue generated by each salesperson?

select name, sum(cost_$) total_revenue
from cars 
join sales on cars.car_id = sales.car_id 
join salespersons on salespersons.salesman_id = sales.salesman_id
group by name
order by total_revenue desc;

-- Question 4. What are the details of the cars sold by each salesperson?

select name, cars.car_id, make, type, style, cost_$
from cars
join sales on cars.car_id = sales.car_id 
join salespersons on salespersons.salesman_id = sales.salesman_id
order by name

-- Question 5. What is the total revenue generated by each car type?

select type as car_type, sum(cost_$) total_revenue
from cars 
group by car_type
order by total_revenue desc;

-- Question 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

select cars.car_id, make, type, style, cost_$
from cars
join sales 
		on cars.car_id = sales.car_id 
join salespersons 
		on salespersons.salesman_id = sales.salesman_id
where 	extract(year from purchase_date) = 2021 
		and name = 'Emily Wong';

-- Question 7. What is the total revenue generated by the sales of hatchback cars?

select style, sum(cost_$) total_revenue
from cars 
where style = 'Hatchback'
group by style

-- Question 8. What is the total revenue generated by the sales of SUV cars in the year 2022?

select sum(cost_$) total_revenue
from cars 
join sales on cars.car_id = sales.car_id 
and style = 'SUV' and extract(year from purchase_date) = 2022

-- Question 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

select name,city, count(car_id) total_car_sold
from sales
join salespersons on sales.salesman_id = salespersons.salesman_id
and extract(year from purchase_date) = 2023
group by name,city
order by total_car_sold desc
limit 1;


-- Question 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

select name, age, sum(cost_$) revenue
from cars 
join sales on cars.car_id = sales.car_id
join salespersons on sales.salesman_id = salespersons.salesman_id
and extract(year from purchase_date) = 2022
group by name, age
order by revenue desc
limit 1;
